Open instagr.am links too
austinhuang0131/barinsta pull request #1113
Opened 2021-04-16 19:00 UTC by tcely

2021-04-16 19:56 UTC, austinhuang0131 requested changes
You also need to edit [this part](https://github.com/austinhuang0131/barinsta/blob/master/app/src/main/java/awais/instagrabber/utils/IntentUtils.java#L14) for the link parser to be functional...

2021-04-24 02:38 UTC, tcely commented
> You also need to edit [this part](https://github.com/austinhuang0131/barinsta/blob/master/app/src/main/java/awais/instagrabber/utils/IntentUtils.java#L14) for the link parser to be functional...

Thanks for the tip!

Is there a reason not to use `android.net.Uri.parse` in that file?

2021-04-24 02:39 UTC, austinhuang0131 commented
It was inherited from InstaGrabber as-is, you can make it use Uri.parse if you want

2021-04-26 21:41 UTC, austinhuang0131 approved these changes

2021-04-26 21:41 UTC, merged