add an alert dialog for swipe up link - fix issue #1101
austinhuang0131/barinsta pull request #1190
Opened 2021-04-30 13:58 UTC by stamatiap

If you have any other suggestions for the message that appears in the dialog, please tell me and I can change it.

2021-05-10 11:56 UTC, ammargitham commented on app/src/main/java/awais/instagrabber/fragments/StoryViewerFragment.java
> +		   		builder.setTitle("Are you sure you want to open this link?");
Extract the string to a string resource

2021-05-10 18:05 UTC, stamatiap commented on app/src/main/java/awais/instagrabber/fragments/StoryViewerFragment.java
> +		   		builder.setTitle("Are you sure you want to open this link?");
Alright, I'll do that right away. But is the message okay? Or should I change it?

2021-05-14 17:56 UTC, austinhuang0131 requested changes
We're on new Java, so you can simply shorten the entire function to a lambda instead of importing an entire module and then declare a variable with various functions. Refer to https://github.com/austinhuang0131/barinsta/blob/master/app/src/main/java/awais/instagrabber/fragments/StoryViewerFragment.java#L220 for a similar dialog implementation

also proper indentations please

2021-05-14 17:56 UTC, austinhuang0131 commented on app/src/main/java/awais/instagrabber/fragments/StoryViewerFragment.java
> +		   			.setNegativeButton("No", dialogClickListener).show();
You don't need to require the same listener on the negative button. In fact you can just use a null...

Also string resources for buttons (They already exist)

```suggestion
		   		AlertDialog.Builder builder = new AlertDialog.Builder(context);
		   		builder.setTitle(R.string.swipe_up_confirmation);
		   		builder.setMessage(tag.toString()).setPositiveButton(R.string.yes, (d, w) -> Utils.openURL(context, tag.toString()))
		   			.setNegativeButton(R.string.no, null).show();
```

Of course, if you're wary about whether the dialog will actually dismiss or not, you can apply a similar lambda function onto the negative button

2021-05-14 18:27 UTC, stamatiap commented on app/src/main/java/awais/instagrabber/fragments/StoryViewerFragment.java
> +		   			.setNegativeButton("No", dialogClickListener).show();
Thank you for the review and the pointers! I'll work on it. 
Also as for the intendations, it looked fine in my IDE, but I guess it changed after I pushed. I'll try to fix that too.

2021-05-18 21:15 UTC, austinhuang0131 approved these changes

2021-05-18 21:15 UTC, merged