Use Uri.parse for IntentUtils.parseUrl
austinhuang0131/barinsta pull request #1201
Opened 2021-05-03 00:12 UTC by tcely

For at least the next release, this is trying to log URLs
that parse differently and use the older results in that case
to prevent any breakage.

Fixes #1178

2021-05-03 00:16 UTC, austinhuang0131 commented
I mean I'll test all known cases in the old method before merging this PR, so I wouldn't worry about that

2021-05-03 00:58 UTC, tcely commented
Alright. I pulled out the logging and the old code then.

2021-05-10 12:00 UTC, ammargitham commented
@austinhuang0131 If you are testing this, this would be a good time to add test cases for it.

2021-05-18 22:47 UTC, austinhuang0131 requested changes
Two fatal flaws. Should've been quite obvious to spot.

2021-05-18 22:47 UTC, austinhuang0131 commented on app/src/main/java/awais/instagrabber/utils/IntentUtils.java
> +        } else if (2 >= paths.size() && "explore".equals(path)) {
There's a very obvious mistake on this line

2021-05-18 22:47 UTC, austinhuang0131 commented on app/src/main/java/awais/instagrabber/utils/IntentUtils.java
> +        String path = paths.get(0);
What if I try to VIEW `https://instagram.com/`?

2021-05-19 17:53 UTC, tcely commented on app/src/main/java/awais/instagrabber/utils/IntentUtils.java
> +        String path = paths.get(0);
As I understand it, the current outcome is to return null, correct?

2021-05-19 17:54 UTC, tcely commented on app/src/main/java/awais/instagrabber/utils/IntentUtils.java
> +        } else if (2 >= paths.size() && "explore".equals(path)) {
I'm not seeing what you mean here. Please explain further.

2021-05-19 17:58 UTC, austinhuang0131 commented on app/src/main/java/awais/instagrabber/utils/IntentUtils.java
> +        String path = paths.get(0);
No! If I try to VIEW `https://instagram.com/`, then `paths` will be an empty list. Getting index 0 of a list of length 0 throws a `IndexOutOfBoundsException`, not returning `null`.

2021-05-19 17:58 UTC, austinhuang0131 commented on app/src/main/java/awais/instagrabber/utils/IntentUtils.java
> +        } else if (2 >= paths.size() && "explore".equals(path)) {
`2 >= paths.size()`

2021-05-19 18:11 UTC, tcely commented on app/src/main/java/awais/instagrabber/utils/IntentUtils.java
> +        String path = paths.get(0);
I was asking about this function. I'm considering adding a check for the empty paths list.

2021-05-19 18:14 UTC, austinhuang0131 commented on app/src/main/java/awais/instagrabber/utils/IntentUtils.java
> +        String path = paths.get(0);
Oh, sorry. Yeah, you can return `null`.

2021-05-19 18:32 UTC, austinhuang0131 commented on app/src/main/java/awais/instagrabber/utils/IntentUtils.java
> +        } else if (2 >= paths.size() && "explore".equals(path)) {
Since you have `paths.get(2)`, you want to make sure the size is > 2, not >= 2.

2021-05-19 18:34 UTC, austinhuang0131 commented on app/src/main/java/awais/instagrabber/utils/IntentUtils.java
> +        String path = paths.get(0);
Try/catch sounds like an overkill to me if one already knows the possible situations. So you can just do an if statement just above this line.

2021-05-19 21:01 UTC, merged