Added filter post function
austinhuang0131/barinsta pull request #814
Opened 2021-03-18 07:55 UTC by zerrium

This code solves #590 

What I did:
1. Added a string array to the res/values/filter_keyword.xml
2. Created a class: FilterKeywords to save all keywords from string array resource file (I created a new package called zerrium however you may move the class and delete the zerrium package)
3. I added a code to get all from string array resource file and save it to the class I made at MainActivity
4. I modified the FeedPostFetchService#fetch#onSuccess method to skip adding posts (media) which the captions contain keyword specified at the string array resource to FeedModels thus hiding it from the FeedFragment

I know this code is still a bit dirty and need finishing (like adding it to settings activity) but for now I will leave it like this and let the maintainers add it

Thank you

2021-03-19 04:18 UTC, zerrium commented
Alright thanks for the hints, next step I will create a dialog with text box so users can fill what keywords and call it from PostPreferencesFragment

2021-03-19 12:06 UTC, zerrium commented
I think that's all what I can do, I know it is still somewhat messy but I tried my best and thanks for the opportunity! 😄

2021-03-20 15:30 UTC, austinhuang0131 requested changes
Just a little conventional stuff. Otherwise, so far so good!

2021-03-20 15:30 UTC, austinhuang0131 commented on app/src/main/res/values/strings.xml
> +    <string name="removed_keywords">Removed keyword: {0} from filter list</string>
In Android Java we use `%s` to indicate a String placeholder and `%d` to indicate a digits placeholder.

```suggestion
    <string name="added_keywords">Added keyword: %s to filter list</string>
    <string name="removed_keywords">Removed keyword: %s from filter list</string>
```

2021-03-20 15:30 UTC, austinhuang0131 commented on app/src/main/java/awais/instagrabber/utils/KeywordsFilterUtils.java
> +        final String temp = c.getText().toLowerCase(LocaleUtils.getCurrentLocale());
Captions can be in any language though?

```suggestion
        final String temp = c.getText().toLowerCase();
```

2021-03-20 15:30 UTC, austinhuang0131 commented on app/src/main/java/awais/instagrabber/fragments/settings/PostPreferencesFragment.java
> +
```suggestion
```

2021-03-20 15:30 UTC, austinhuang0131 commented on app/src/main/java/awais/instagrabber/adapters/KeywordsFilterAdapter.java
> +            final String message = context.getString(R.string.removed_keywords).replace("{0}", s);
In pursuant to my suggestion in `string.xml`, this would be:

```suggestion
            final String message = context.getString(R.string.removed_keywords, s);
```

See [Android Developers](https://developer.android.com/reference/android/content/Context#getString(int,%20java.lang.Object...)).

2021-03-20 15:30 UTC, austinhuang0131 commented on app/src/main/java/awais/instagrabber/adapters/KeywordsFilterAdapter.java
> +        holder.getTextView().setText(items.get(position));
The convention here is to have a `bind` function on the ViewHolder instead of handling it on the Adapter. Also, we pass OnClickListener from the fragment.

Example: [Adapter.onBindViewHolder](https://github.com/austinhuang0131/barinsta/blob/master/app/src/main/java/awais/instagrabber/adapters/NotificationsAdapter.java#L50) and [ViewHolder.bind](https://github.com/austinhuang0131/barinsta/blob/master/app/src/main/java/awais/instagrabber/adapters/viewholder/NotificationViewHolder.java#L23). More specifically:

- Draw the ViewHolder and add OnClickListener in ViewHolder.bind
- Define the OnClickListener in Fragment, then pass it to Adapter, the pass it to ViewHolder.bind

2021-03-20 18:12 UTC, austinhuang0131 commented
Nothing has changed? Did you forget to push?

2021-03-20 18:14 UTC, zerrium commented
> 
> 
> Nothing has changed? Did you forget to push?

Let me check one more time...

2021-03-20 18:45 UTC, zerrium commented
Alright, this code should be fine and I have rechecked but I can't test the updated code you suggested because the app crashed, it says about EmojiParser NPE

2021-03-20 18:46 UTC, austinhuang0131 commented
yeah i'll test it for you once that gets away

2021-03-21 23:56 UTC, austinhuang0131 approved these changes

2021-03-22 00:27 UTC, austinhuang0131 commented
I guess it's good enough for a beginner. Improvements I've made:

* Move filter function to PostsRecyclerView so that it can apply on _all_ post views (incl. hashtags, profile, etc.)
* Use [ConstraintLayout](https://developer.android.com/training/constraint-layout) instead of several layers of various layouts
* Specify window size (80% of screen)
* `48dp` is quite large for the buttons lol

Good luck on your career!

2021-03-22 00:27 UTC, merged