Feature/option prepend username
austinhuang0131/barinsta pull request #925
Opened 2021-03-31 16:31 UTC by junhuicoding

Features added based on https://github.com/austinhuang0131/barinsta/issues/631:
- Added a user setting for pretending username to downloaded filenames.
![image](https://user-images.githubusercontent.com/54289027/113177937-a4021080-9280-11eb-9edc-c0be3ef02d01.png)
When turned on (Tested on albums, stories, video and image posts):
![image](https://user-images.githubusercontent.com/54289027/113178035-c09e4880-9280-11eb-9f53-35296cc43a98.png)
When turned off:
![image](https://user-images.githubusercontent.com/54289027/113178106-d1e75500-9280-11eb-9202-9e0ed8a0213d.png)

- The current language for the setting is only in English `Prepend Username to Filename`, will need to be translated in the respective `strings.xml` files

- ~~Added a null check for `profileModel` in `ProfileFragment.fetchProfileDetails()` as I was running into issues displaying the profile tab when I re-ran the app from android studios when logged in previously. App will just crash. Might want to look into it a bit further, but this null check should not be significant, it just prevents a crash.~~

Additional comments:
This is my first time working on an android app, any suggestions, comments or improvements to be made are extremely welcomed!

2021-03-31 16:37 UTC, junhuicoding commented
ProfileFragment.fetchProfileDetails() has been fixed in master.

2021-04-02 13:33 UTC, austinhuang0131 requested changes
Thank you for your contributions.

One thing you missed is that Barinsta does depend on file name to check if a media (only for posts, not stories and stuff) is downloaded or not, through `DownloadUtils$checkDownloaded`. You want to make sure it successfully checks for the downloaded status.

2021-04-02 13:33 UTC, austinhuang0131 commented on app/src/main/java/awais/instagrabber/fragments/settings/DownloadsPreferencesFragment.java
> +        preference.setTitle("Prepend Username to Filename");
```suggestion
        preference.setTitle(R.string.download_prepend_username);
```

2021-04-02 13:33 UTC, austinhuang0131 commented on app/src/main/java/awais/instagrabber/utils/DownloadUtils.java
> +        final String usernamePrepend = "".equals(username) ? "" : "@" + username + "_";
```suggestion
        final String usernamePrepend = TextUtils.isEmpty(username) ? "" : "@" + username + "_";
```

2021-04-02 17:24 UTC, junhuicoding commented on app/src/main/java/awais/instagrabber/fragments/settings/DownloadsPreferencesFragment.java
> +        preference.setTitle("Prepend Username to Filename");
Fixed!

2021-04-02 17:24 UTC, junhuicoding commented on app/src/main/java/awais/instagrabber/utils/DownloadUtils.java
> +        final String usernamePrepend = "".equals(username) ? "" : "@" + username + "_";
Fixed!

2021-04-02 18:25 UTC, junhuicoding commented
> Thank you for your contributions.
> 
> One thing you missed is that Barinsta does depend on file name to check if a media (only for posts, not stories and stuff) is downloaded or not, through `DownloadUtils$checkDownloaded`. You want to make sure it successfully checks for the downloaded status.

Thanks for the feedback! I've added your suggested changes, as well as included the `usernamePrepend` string to `getDownloadChildSaveFile` correctly for `MEDIA_TYPE_SLIDER`.  `MEDIA_TYPE_IMAGE` and  `MEDIA_TYPE_VIDEO` were already added.

This will not flag a downloaded item correctly if a user changes the setting to prepend username after downloading some files due to a mismatch in names. This is the same as the other download settings related to changing of folders. This should not have a large impact as users are unlikely to switch between these settings regularly. As of now, the feature works in correctly displaying downloaded icon for files downloaded when the settings at time of download are the same as the current settings.

- One potential fix for the prepending option will be to search for the existent of both filenames, with and without username prepend (simple to implement)
- Checking for the username specific folder will possible to implement too, just check for both the username folder as well as general folder
- The issue for a custom folder would be tricky, as there is no history of all previously selected folders. It might be possible to check for all folders that barinsta has permission to write into, but I am not too sure about this route.

2021-04-02 19:24 UTC, austinhuang0131 commented
Oh, you're thinking too much... We're just talking current folder and assume it's not renamed

2021-04-02 20:06 UTC, junhuicoding commented
> Oh, you're thinking too much... We're just talking current folder and assume it's not renamed
> 
> So, yes, check with and without username, c'est tout (and username-specific folder as well as current custom folder is already implemented within)

Thanks for the clarifications! I've updated the changes requested for checking with and without username.

2021-04-03 16:51 UTC, austinhuang0131 approved these changes

2021-04-03 16:51 UTC, merged